name: Node.js Package

env:
  CI: true

on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
      # - uses: bduff9/use-npmrc@v1.1
      #   with:
      #     dot-npmrc: ${{ secrets.DOT_NPMRC }}
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: npm publish
      - run: npx can-npm-publish --verbose && npm publish || echo "No need to publish"
        env:
          # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: set version to env
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: add version tag
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
